# Parsing APIs Example

## Intro

Now we will take a look on a real data. When you parse data from web you will often meet API based web-pages. 

For example [zalando.fr](https://www.zalando.fr/accueil-homme/) is API based web-page. 

In this guided lab you will learn how to obtain the links from webpages and extract the data. Read through this doc, execute the cells in order and make sure you understand the explanations. 

*Note: This guided lab uses Google Chrome. Other browsers like Safari and Firefox have similar tools for developers but they work differently. To save your time in following this lab, it is strongly recommended that you install and use Google Chrome.*

## Obtaining the link

Zalando is discount e-store where you can buy clothes and accesories with discount. When we go to the web-page, we can choose different sections. First the general process will be shown using [Children section](https://www.zalando.fr/accueil-enfant/) as example.

Here we will parse data about promotions only. Therefore, final output will be the DataFrame with all the goods under discount.

[![Image from Gyazo](https://i.gyazo.com/fa4874d8e81c7570273bbfb853d66308.png)](https://gyazo.com/fa4874d8e81c7570273bbfb853d66308)


We go to Promos page. Right click of mouse shows us a list of actions possible, from which we select Inspect.

<img src='https://i.gyazo.com/bccbd11d69c9040dc98758d443e32052.png' width="400">


You will see the menu dropdown on the right side or on the bottom of the window. There you should click on Network:


[![Image from Gyazo](https://i.gyazo.com/f7e0db81cbfee67694183d1a7640bf81.png)](https://gyazo.com/f7e0db81cbfee67694183d1a7640bf81)

Right after the developer part will change showing the files behind the page. In order to obtain only useful files we select the following settings:
1. Preserve Log
2. Select XHR files.

[![Image from Gyazo](https://i.gyazo.com/9a899d4441d9d93e795f79747f1e47d5.png)](https://gyazo.com/9a899d4441d9d93e795f79747f1e47d5)

In order to obtain some files we need to scrool down and go forward to second page. 

[![Image from Gyazo](https://i.gyazo.com/0956eb3d5125075a236c9a439c7749c7.png)](https://gyazo.com/0956eb3d5125075a236c9a439c7749c7)

In the Network panel you can see the following files being uploaded. All the data on the web-page is uploaded from the json file, which is one of the following. It is important to understand which file contains what kind of information. 

<a href="https://gyazo.com/cf97a655869f0b22df0ada1cb2a41c3c"><img src="https://i.gyazo.com/cf97a655869f0b22df0ada1cb2a41c3c.png" alt="Image from Gyazo" width="724.8"/></a>

When you find what kind of information you need for the data to be uploaded you just test it. Here we need the article... file:

<a href="https://gyazo.com/78b35bf492994b3f35c0564a21da202a"><img src="https://i.gyazo.com/78b35bf492994b3f35c0564a21da202a.png" alt="Image from Gyazo" width="727.2"/></a>

When we test the link in Chrome inkognito mode we obtain the proper json file:


<a href="https://gyazo.com/b60453fa98454fa29771c731a5174443"><img src="https://i.gyazo.com/b60453fa98454fa29771c731a5174443.png" alt="Image from Gyazo" width="1530.4"/></a>

In order to change the objects in the json file (kind of pagination), you need to change the offset (the number of the first element on the page). in fact, if you take a look on the link, it is easy to unerstand the structure of the link.

# Reading the data

Now the party rocks! When we know how can we obtain the data, it is not a problem to obtain the whole database with all the data from the web-page.
In this lab you will collect your database of Zalando products. You select which goods you want to track. You can define as many filters to your data as you want. Just make sure that the data represents the filters.

In [1]:
import json
import requests
import pandas as pd
from pandas.io.json import json_normalize

In [2]:
'''
L.S. Good, but halfway the code stops working. 
'''

# Paste the url you obtained for your data
#url='https://www.zalando.fr/api/catalog/articles?categories=promo-enfant&limit=84&offset=84&sort=sale'
ur_l = "http://api.stackexchange.com/2.2/questions?todate=1571011200&order=desc&sort=activity&tagged=python&site=stackoverflow"
url_2 = "http://www.recipepuppy.com/api/?i=onions,garlic&q=omelet&p=3"

#### Collect first 84 object of the of the data (1st page)

Your output should be a Pandas DataFrame of goods. Each row should contain only text or numbers, having *family_articles, flags, media* and *sizes* remaining lists (they are exceptions).

In [3]:
# Your code

response = requests.get(url_2)    
results_url = response.json()
results_url

{'href': 'http://www.recipepuppy.com/',
 'results': [],
 'title': 'Recipe Puppy',
 'version': 0.1}

In [4]:
data = pd.DataFrame(results_url)
data.head()

Empty DataFrame
Columns: [href, results, title, version]
Index: []

In [5]:
def flatten(data, col_list):
    for column in col_list:
        flattened = pd.DataFrame(dict(data[column])).transpose()
        columns = [str(col) for col in flattened.columns]
        flattened.columns = [column + '_' + colname for colname in columns]
        data = pd.concat([data, flattened], axis=1)
        data = data.drop(column, axis=1)
    return data

In [6]:
nested_columns = ['results']

flat = flatten(data, nested_columns)
flat.head()

Empty DataFrame
Columns: [href, title, version]
Index: []

In [7]:
"""
For example:
http://www.recipepuppy.com/api/?i=onions,garlic&q=omelet&p=3

Optional Parameters:
i : comma delimited ingredients
q : normal search query
p : page
format=xml : if you want xml instead of json

"""

url_3 = "http://www.recipepuppy.com/api/?i=sugar &q=pasta &p=3"

from pandas.io.json import json_normalize
response = requests.get(url_3)
results = response.json()
ls = []
# this is a shorter way to read json files than with flatternm you do not nead to define a function anymore 
flattened_data = json_normalize(results)
#flattened_data2 = json_normalize(results, results)
# hier zie je de kolommen om snel te zien welke nested zijn. In dit geval is het alleen "results"
flattened_data

                          href results         title  version
0  http://www.recipepuppy.com/      []  Recipe Puppy      0.1

In [8]:
# zo kan je de kolom "results" uitvouwen 
flattened_data_1 = json_normalize(flattened_data.results[0])

#flattened_data_2 = json_normalize(flattened_data, ls)

flattened_data_1.head(10)

Empty DataFrame
Columns: []
Index: []

In [9]:
url_beer = "https://api.openbrewerydb.org/breweries"

url_jokes = "https://api.icndb.com"

from pandas.io.json import json_normalize
response = requests.get(url_beer)
results = response.json()

beer_data = json_normalize(results)

beer_data

,brewery_type,city,country,id,latitude,longitude,name,phone,postal_code,state,street,tag_list,updated_at,website_url
0,micro,Birmingham,United States,2,33.524521,-86.774322,Avondale Brewing Co,2057775456,35222-1932,Alabama,201 41st St S,[],2018-08-23T23:19:57.825Z,http://www.avondalebrewing.com
1,micro,Tuscaloosa,United States,4,33.1984907123707,-87.5621551272424,Band of Brothers Brewing Company,2052665137,35401-4653,Alabama,1605 23rd Ave,[],2018-08-23T23:19:59.462Z,http://www.bandofbrosbrewing.com
2,micro,Birmingham,United States,44,33.5128492349817,-86.7914000624146,Trim Tab Brewing,2057030536,35233-3401,Alabama,2721 5th Ave S,[],2018-08-23T23:20:31.423Z,http://www.trimtabbrewing.com
3,micro,Huntsville,United States,46,34.7277523,-86.5932014,Yellowhammer Brewery,2569755950,35805-3046,Alabama,2600 Clinton Ave W,[],2018-08-23T23:20:33.102Z,http://www.yellowhammerbrewery.com
4,micro,Wasilla,United States,55,61.5752695,-149.4127103,Bearpaw River Brewing Co,,99654-7679,Alaska,4605 E Palmer Wasilla Hwy,[],2018-08-23T23:20:40.743Z,http://bearpawriverbrewing.com
5,micro,Anchorage,United States,76,61.1384893547315,-149.879076042937,King Street Brewing Co,9073365464,99515,Alaska,9050 King Street,[],2018-08-23T23:20:57.179Z,http://www.kingstreetbrewing.com
6,micro,Tucson,United States,94,32.2467372722906,-110.992750525872,1912 Brewing,5202564851,85745-1444,Arizona,2045 N Forbes Blvd Ste 105,[],2018-08-23T23:21:11.302Z,http://www.1912brewing.com
7,contract,Scottsdale,United States,98,33.4972615652174,-111.924474347826,Bad Water Brewing,5207459175,85251-3914,Arizona,4216 N Brown Ave,[],2018-08-23T23:21:15.169Z,http://www.badwaterbrewing.com
8,brewpub,Chandler,United States,104,33.3053455,-111.911126,BJs Restaurant & Brewery - Chandler,4809170631,85226-5175,Arizona,3155 W Chandler Blvd,[],2018-08-23T23:21:21.165Z,http://www.bjsrestaurants.com
9,micro,Tucson,United States,107,32.201608314954,-110.821778571134,BlackRock Brewers,5202073203,85710-6767,Arizona,1664 S Research Loop Ste 200,[],2018-08-23T23:21:23.794Z,http://www.brb.beer
10,micro,Tucson,United States,127,32.2504946147872,-111.005452051979,Dragoon Brewing Co,5203293606,85745-1214,Arizona,1859 W Grant Rd Ste 111,[],2018-08-23T23:21:40.563Z,http://www.dragoonbrewing.com
11,micro,Williams,United States,141,35.2500282,-112.1892168,Grand Canyon Brewing Company,8005132072,86046-2530,Arizona,233 W Route 66,[],2018-08-23T23:21:53.397Z,http://www.grandcanyonbrewingco.com
12,micro,Lake Havasu City,United States,163,34.4689736300844,-114.342433477881,Mudshark Brewing Co,9284532981,86403-0966,Arizona,210 Swanson Ave,[],2018-08-23T23:22:12.542Z,http://www.mudsharkbrewingco.com
13,micro,Peoria,United States,182,33.6687744976834,-112.238054093359,Richter Aleworks,6029086553,85382-7434,Arizona,8279 W Lake Pleasant Pkwy Ste 110,[],2018-08-23T23:22:29.385Z,http://www.richteraleworks.com
14,regional,Chandler,United States,187,33.3032436,-111.8423459,SanTan Brewing Co,4809178700,85225-7862,Arizona,8 S San Marcos Pl,[],2018-08-23T23:22:33.482Z,http://www.santanbrewing.com
15,brewpub,Surprise,United States,198,33.63822125,-112.357813820157,State 48 Brewery,6235841095,85374-3873,Arizona,13823 W Bell Rd,[],2018-08-23T23:22:41.468Z,
16,micro,Phoenix,United States,219,33.516633,-112.0301125,Wren House Brewing Company,6022449184,85008-2713,Arizona,2125 N 24th St,[],2018-08-23T23:22:59.255Z,http://www.wrenhousebrewing.com
17,brewpub,Paragould,United States,225,36.0316358142169,-90.5204797204622,Brick Oven Pizza Co / Brick & Forge Brewing,8702364200,72450-6122,Arkansas,2410 Linwood Dr,[],2018-08-23T23:23:05.438Z,http://www.brickovenpizzacompany.com
18,micro,North Little Rock,United States,235,34.7594277548278,-92.2726892120821,Diamond Bear Brewing Co,5017082739,72114-5381,Arkansas,600 N Broadway St,[],2018-08-23T23:23:14.931Z,http://www.diamondbear.com
19,micro,Little Rock,United States,247,34.742845,-92.260019,Lost Forty Brewing,5013197275,72202,Arkansas,501 Byrd St,[],2018-08-23T23:23:24.018Z,http://www.lost40brewing.com/

#### Collect all the objects from selected filters. Total number of pages can be found in the same json. Use *sku* column as index.

Your output should be a Pandas DataFrame of goods. Each row should contain only text or numbers, having family_articles, flags, media and sizes remaining lists (they are exceptions).

In [10]:
# Get the total number of pages
total_pages=results['pagination']['page_count']

# Your code
df=pd.DataFrame()
for i in range(total_pages):
    k=84*i
    url=f'https://www.zalando.fr/api/catalog/articles?categories=promo-enfant&limit=84&offset={k}&sort=sale'
    response = requests.get(url)
    results = response.json()
    flattened_data = json_normalize(results)
    flattened_data1 = json_normalize(flattened_data.articles[0])
    flattened_data1=flattened_data1.set_index('sku')
    df = df.append(flattened_data1)

df

TypeError: list indices must be integers or slices, not str

#### Display the trending brand in DataFrame

In [11]:
df.brand_name.value_counts().index[0]

NameError: name 'df' is not defined

#### Display the brand with maximal total discount (sum of discounts on all goods)

In [12]:
#Our data is still text. Convert prices into numbers:
df['price.original']=df['price.original'].str.extract('(\d*,\d*)')
df['price.promotional']=df['price.promotional'].str.extract('(\d*,\d*)')

df['price.original'] = [x.replace(',', '.') for x in df['price.original']]
df['price.promotional'] = [x.replace(',', '.') for x in df['price.promotional']]

NameError: name 'df' is not defined

In [13]:
df['discount_amount']=df['price.original'].astype(float)-df['price.promotional'].astype(float)
df1=df.copy()

NameError: name 'df' is not defined

In [14]:
total_disc=df1.groupby(['brand_name']).sum().discount_amount

NameError: name 'df1' is not defined

In [ ]:
total_disc.sort_values(ascending=False).index[0]

#### Display the brands without discount at all

In [ ]:
total_disc[total_disc==0]